### ISSUE TITLE
安装时读完条之后会卡住

### ISSUE THREAD

**Issue by ckn4** [RANSAA/OpenCore#1]
使用EFI版本：opencore0.6.7版本EFI
安装mac版本：big sur
出现问题：使用神舟z6-sl7d1，除所要安装的固态外均为原装配件。安装时可以正常出现苹果logo，但是读条读一会儿会进入一个紫色的空白界面，只有鼠标指针，且鼠标指针可以正常移动，按键盘上任何键都没有反应。始终卡在这个界面，只能长按开机键强制关闭。
重启多次仍然复现，无法正常安装。
是因为EFI不支持11版本吗？在网上也没有搜索到同样问题的网友，您知道这是哪里出了问题吗？

**Comment by RANSAA** [comment]
> 埃菲 · 罗尔： 开放核心 0.6.7E
> 菲
> 马克 · 伊斯塔克斯 · 伊兹 · 格罗斯 · 斯波尔： 伊万兹 6 - sl7d1， 科尔斯 · 克林 · 克林特 · 乌林特 · 多林特 · 科尔多斯安装时可以正常出现苹果logo，但是读条读一会儿会进入一个紫色的空白界面，只有鼠标指针，且鼠标指针可以正常移动，按键盘上任何键都没有反应。始终卡在这个界面，只能长按开机键强制关闭。
> 多点小马， 多特人。
> EFI 和 111 次要求？

可以正常安装了吗？？
